package br.gov.mj.sinca;

public interface ConstantSinca {

	public String LISTA_ESTADO_CIVIL ="LISTA_ESTADO_CIVIL";
	public String LISTA_UF = "LISTA_UF";
	public String LISTA_LOCALIZACAO = "LISTA_LOCALIZACAO"; 
	public String LISTA_ENDERECO = "LISTA_ENDERECO";
	public String LISTA_TIPO_ENDERECO = "LISTA_TIPO_ENDERECO";
	
	//Anistiado
	public String LISTA_ENDERECO_ANISTIADO = "LISTA_ENDERECO_ANISTIADO";
	public String LISTA_TIPO_ENDERECO_ANISTIADO = "LISTA_TIPO_ENDERECO_ANISTIADO";
	public String LISTAR_PESSOA_ANISTIADO = "LISTAR_PESSOA_ANISTIADO";
	public String LISTA_TIPO_DOCUMENTO_ANISTIADO = "LISTA_TIPO_DOCUMENTO_ANISTIADO";
	public String LISTA_TIPO_TELEFONE_ANISTIADO = "LISTA_TIPO_TELEFONE_ANISTIADO";
	public String LISTA_DOCIUMENTOS_ANISTIADO = "LISTA_DOCIUMENTOS_ANISTIADO";
	public String LISTA_TELEFONES_ANISTIADO = "LISTA_TELEFONES_ANISTIADO";
	public String PESSOA_SALVA_ANISTIADO_PROPOSTA = "PESSOA_SALVA_ANISTIADO_PROPOSTA";

	//REQUERENTE
	public String LISTA_ENDERECO_REQUERENTE = "LISTA_ENDERECO_REQUERENTE";
	public String LISTA_TIPO_ENDERECO_REQUERENTE = "LISTA_TIPO_ENDERECO_REQUERENTE";
	public String LISTAR_PESSOA_REQUERENTE = "LISTAR_PESSOA_REQUERENTE";
	public String LISTA_TIPO_DOCUMENTO_REQUERENTE = "LISTA_TIPO_DOCUMENTO_REQUERENTE";
	public String LISTA_TIPO_TELEFONE_REQUERENTE = "LISTA_TIPO_TELEFONE_REQUERENTE";
	public String LISTA_DOCIUMENTOS_REQUERENTE = "LISTA_DOCIUMENTOS_REQUERENTE";
	public String LISTA_TELEFONES_REQUERENTE = "LISTA_TELEFONES_REQUERENTE";
	public String PESSOAS_SALVAS_REQUERENTE_PROPOSTA = "PESSOAS_SALVAS_REQUERENTE_PROPOSTA";
	
	//PROCURADOR
	public String LISTA_ENDERECO_PROCURADOR = "LISTA_ENDERECO_PROCURADOR";
	public String LISTA_TIPO_ENDERECO_PROCURADOR = "LISTA_TIPO_ENDERECO_PROCURADOR";
	public String LISTAR_PESSOA_PROCURADOR = "LISTAR_PESSOA_REQUERENTE";
	public String LISTA_TIPO_DOCUMENTO_PROCURADOR = "LISTA_TIPO_DOCUMENTO_PROCURADOR";
	public String LISTA_TIPO_TELEFONE_PROCURADOR = "LISTA_TIPO_TELEFONE_PROCURADOR";
	public String LISTA_DOCIUMENTOS_PROCURADOR = "LISTA_DOCIUMENTOS_PROCURADOR";
	public String LISTA_TELEFONES_PROCURADOR = "LISTA_TELEFONES_PROCURADOR";
	public String PESSOAS_SALVAS_PROCURADOR_PROPOSTA = "PESSOAS_SALVAS_PROCURADOR_PROPOSTA";
	
	//DILIGENCIADO
	public String LISTA_ENDERECO_DILIGENCIADO= "LISTA_ENDERECO_DILIGENCIADO";
	public String LISTA_TIPO_ENDERECO_DILIGENCIADO= "LISTA_TIPO_ENDERECO_DILIGENCIADO";
	public String LISTAR_PESSOA_DILIGENCIADO= "LISTAR_PESSOA_REQUERENTE";
	public String LISTA_TIPO_DOCUMENTO_DILIGENCIADO= "LISTA_TIPO_DOCUMENTO_DILIGENCIADO";
	public String LISTA_TIPO_TELEFONE_DILIGENCIADO= "LISTA_TIPO_TELEFONE_DILIGENCIADO";
	public String LISTA_DOCIUMENTOS_DILIGENCIADO= "LISTA_DOCIUMENTOS_DILIGENCIADO";
	public String LISTA_TELEFONES_DILIGENCIADO= "LISTA_TELEFONES_DILIGENCIADO";
	public String PESSOAS_SALVAS_DILIGENCIADO_PROPOSTA = "PESSOAS_SALVAS_DILIGENCIADO_PROPOSTA";
	


}
